# https://taskfile.dev

version: '3'

# add preconditions to tasks
tasks:
  sys:init:
    desc: Initialize system
    cmds:
      - cmd: echo "TODO init dotfiles zsh tmux vimrc powershellrc etc"
      # TODO update xcode tools
        silence: true

  sys:tasks:  
    desc: Run system tasks
    cmds:
      - cmd: "rm -rf ~/.devtasks && mkdir ~/.devtasks && cp -rf ./Taskfile.yml ~/.devtasks"
      # TODO: append alias if not exists
        silence: true

  system:update:
    desc: Update system packages
    cmds:
      - cmd: echo "TODO update tasks brew asdf-plugins vscode-profile user-settings dotfiles-changes"
      # TODO update xcode tools
        silence: true

  system:config:
    desc: Configure system settings
    cmds:
      - cmd: defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false 
        desc: Disable press and hold for VSCode
        silence: true
      # - cmd: defaults write -g ApplePressAndHoldEnabled -bool false   
      - cmd: |
          if ! gum confirm "Increasing key rate allow you type faster would you like continue?"; then
            defaults write -g KeyRepeat -int 2
            defaults write -g InitialKeyRepeat -int 20
          fi
        desc: Increase key repeat rate
        silence: true
